blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/cunderw/flutter_weather_channel/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/cunderw/flutter_weather_channel/blob/main/README.md
    about: Read the project documentation
